### ISSUE TITLE
Tool require inoperant: path resolution error

### ISSUE THREAD

**Issue by EternalQuasar0206** [MelonRuntime/MelonRuntime#39]
After 96da2b15a8bedb37cbae9eb0899e7804965e53d0

## Stack Tracing

```
> [Unknown Internal Exception] Read failed. The target file "./test.js" does not exist. 

   at MelonJs.Static.Tools.FileSystem.MelonFileManager.ReadText(String target) in C:\Users\Usu�rio\AppData\Roaming\npm\node_modules\melon-runtime\MelonJs.Static\Tools\FileSystem\MelonFileManager.cs:line 55
--- End of stack trace from previous location ---
   at Jint.Runtime.ExceptionHelper.ThrowMeaningfulException(Engine engine, TargetInvocationException exception)
   at Jint.Runtime.Interop.DelegateWrapper.Call(JsValue thisObject, JsValue[] jsArguments)
   at Jint.Engine.Call(FunctionInstance functionInstance, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Engine.Call(ICallable callable, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateCall(EvaluationContext context, JsValue func, Object reference, NodeList`1& arguments, Boolean tailPosition)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.Call(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue(EvaluationContext context)
   at Jint.Runtime.Interpreter.Statements.JintReturnStatement.ExecuteInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.JintStatementList.Execute(EvaluationContext context)
   at Jint.Runtime.Interpreter.JintFunctionDefinition.Execute(EvaluationContext context)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArgument, JsValue[] arguments)
   at Jint.Engine.Call(FunctionInstance functionInstance, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Engine.Call(ICallable callable, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateCall(EvaluationContext context, JsValue func, Object reference, NodeList`1& arguments, Boolean tailPosition)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.Call(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintConditionalExpression.EvaluateInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue(EvaluationContext context)
   at Jint.Runtime.Interpreter.Statements.JintVariableDeclaration.ExecuteInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.JintStatementList.Execute(EvaluationContext context)
   at Jint.Runtime.Interpreter.JintFunctionDefinition.Execute(EvaluationContext context)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArgument, JsValue[] arguments)
   at Jint.Engine.Call(FunctionInstance functionInstance, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Engine.Call(ICallable callable, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateCall(EvaluationContext context, JsValue func, Object reference, NodeList`1& arguments, Boolean tailPosition)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.Call(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue(EvaluationContext context)
   at Jint.Runtime.Interpreter.Statements.JintVariableDeclaration.ExecuteInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.JintStatementList.Execute(EvaluationContext context)
   at Jint.Runtime.Interpreter.JintFunctionDefinition.Execute(EvaluationContext context)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArgument, JsValue[] arguments)
   at Jint.Engine.Call(FunctionInstance functionInstance, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Engine.Call(ICallable callable, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateCall(EvaluationContext context, JsValue func, Object reference, NodeList`1& arguments, Boolean tailPosition)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.Call(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue(EvaluationContext context)
   at Jint.Runtime.Interpreter.Expressions.JintAssignmentExpression.SimpleAssignmentExpression.AssignToIdentifier(EvaluationContext context, JintIdentifierExpression left, JintExpression right, Boolean hasEvalOrArguments)
   at Jint.Runtime.Interpreter.Statements.JintVariableDeclaration.ExecuteInternal(EvaluationContext context)
   at Jint.Runtime.Interpreter.JintStatementList.Execute(EvaluationContext context)
   at Jint.Engine.<>c__DisplayClass65_0.<Execute>g__DoInvoke|0()
   at Jint.Engine.ExecuteWithConstraints[T](Func`1 callback)
   at Jint.Engine.Execute(Script script)
   at Jint.Engine.Execute(String source, ParserOptions parserOptions)
   at Jint.Engine.Execute(String source)
   at MelonJs.JavaScript.Containers.JintContainer.Execute(String script) in C:\Users\Usu�rio\AppData\Roaming\npm\node_modules\melon-runtime\MelonJs.JavaScript\Containers\JintContainer.cs:line 81
```

**Comment by EternalQuasar0206** [comment]
Solution brainstorm: use `__basedir__` to get the definitive path and directly get the modules

**Comment by EternalQuasar0206** [comment]
For now, all the path resolutions should use `application.baseDir()` as base
